"""Personalized roadmap page — pathfinder agent + checkable milestones."""
from __future__ import annotations

import html as _html

import streamlit as st

from . import state as S
from .components import card, empty_state, section_header, step, _render_html
from ..data import domain_detail, role_detail


def _generate_plan(force_label: str) -> None:
    """Run the pathfinder, save the plan, and force a clean rerender.

    Wrapping the call lets us surface failures in the UI rather than letting
    a silent exception turn the button into a no-op.
    """
    p = S.profile()
    try:
        with st.spinner(f"{force_label}…"):
            plan = S.orch().make_plan(p)
    except Exception as exc:  # noqa: BLE001
        st.error(f"Could not generate the roadmap: {exc}")
        return
    S.st.session_state[S.K_PLAN] = plan
    S.st.session_state[S.K_MILESTONE_PROGRESS] = {
        i: False for i in range(len(plan.milestones))
    }
    st.toast("Roadmap updated.", icon="✨")
    st.rerun()


def _render_profile_chip(p) -> None:
    """Tiny profile recap so users can see their inputs were actually used."""
    domain_name = (domain_detail(p.preferred_domain) or {}).get("name", "—")
    role_name = (role_detail(p.target_role) or {}).get("name", "—")
    bits = [
        ("Domain", domain_name),
        ("Role", role_name),
        ("Hours/week", str(p.weekly_hours)),
        ("Timeline", f"{p.timeline_weeks} wks"),
        ("Budget", f"${p.budget_usd}"),
    ]
    items = "".join(
        f'<span class="cg-tag info"><b>{_html.escape(k)}</b>&nbsp;'
        f'<span style="opacity:.85;">{_html.escape(v)}</span></span>'
        for k, v in bits
    )
    _render_html(
        f'<div style="display:flex; flex-wrap:wrap; gap:6px; margin: 4px 0 14px 0;">{items}</div>'
    )


def render() -> None:
    section_header(
        "Your personalized roadmap",
        "Generated by the Pathfinder agent. Re-plan whenever your situation changes.",
    )

    p = S.profile()
    if not (p.preferred_domain or p.target_role):
        clicked = empty_state(
            "Tell us your domain and target role first, and the Pathfinder will build a roadmap.",
            action_label="Go to Profile →",
            on_action_key="roadmap_to_profile",
        )
        if clicked:
            S.st.session_state[S.K_PAGE] = "Profile"
            st.rerun()
        return

    _render_profile_chip(p)

    c1, c2 = st.columns([1, 1])
    with c1:
        if st.button("✨ Generate roadmap", use_container_width=True, key="gen_plan"):
            _generate_plan("Pathfinder is drafting your roadmap")
    with c2:
        replan_disabled = S.st.session_state[S.K_PLAN] is None
        if st.button(
            "🔄 Re-plan with current profile",
            use_container_width=True,
            key="replan",
            disabled=replan_disabled,
            help="Re-runs the Pathfinder using your latest profile.",
        ):
            _generate_plan("Re-planning")

    plan = S.st.session_state[S.K_PLAN]
    if plan is None:
        empty_state("No roadmap yet — click Generate to build one.")
        return

    card(
        "Plan summary",
        f"<span class='cg-muted'>{_html.escape(plan.summary)}</span>"
        + (
            f"<br><br><b>Next action:</b> {_html.escape(plan.next_action)}"
            if plan.next_action
            else ""
        ),
        tags=[("watsonx", "info"), (f"{len(plan.milestones)} milestones", "ok")],
    )

    progress = S.st.session_state[S.K_MILESTONE_PROGRESS]
    if plan.milestones:
        done = sum(1 for v in progress.values() if v)
        st.progress(
            done / max(1, len(plan.milestones)),
            text=f"{done} / {len(plan.milestones)} milestones marked complete",
        )

    for i, m in enumerate(plan.milestones, 1):
        step(i, m.title, m.week_range, m.objectives, m.evidence, m.rationale)
        checked = st.checkbox(
            f"Mark Milestone {i} complete",
            value=progress.get(i - 1, False),
            key=f"ms_done_{i-1}",
        )
        progress[i - 1] = checked

    if plan.risks:
        risks_html = "<ul style='margin: 4px 0 0 18px;'>" + "".join(
            f"<li>{_html.escape(r)}</li>" for r in plan.risks
        ) + "</ul>"
        card("Risks the agent flagged", risks_html, tags=[("Be aware", "warn")])

    _render_html('<div class="cg-divider"></div>')
    st.caption(
        "Disagree with the plan? Tell the agent in Chat or refine your profile and re-plan."
    )
