"""Personalized roadmap page — pathfinder agent + checkable milestones."""
from __future__ import annotations

import streamlit as st

from . import state as S
from .components import section_header, step, empty_state, card


def render() -> None:
    section_header("Your personalized roadmap", "Generated by the Pathfinder agent. Re-plan whenever your situation changes.")

    p = S.profile()
    if not (p.preferred_domain or p.target_role):
        empty_state(
            "Tell us your domain and target role first, and the Pathfinder will build a roadmap.",
            action_label="Go to Profile →",
            on_action_key="roadmap_to_profile",
        ) and (S.st.session_state.update({S.K_PAGE: "Profile"}), st.rerun())
        return

    c1, c2 = st.columns([1, 1])
    with c1:
        if st.button("✨ Generate roadmap", use_container_width=True, key="gen_plan"):
            with st.spinner("Pathfinder is drafting your roadmap…"):
                plan = S.orch().make_plan(p)
                S.st.session_state[S.K_PLAN] = plan
                S.st.session_state[S.K_MILESTONE_PROGRESS] = {
                    i: False for i in range(len(plan.milestones))
                }
    with c2:
        if S.st.session_state[S.K_PLAN] is not None:
            if st.button("🔄 Re-plan with current profile", use_container_width=True, key="replan"):
                with st.spinner("Re-planning…"):
                    plan = S.orch().make_plan(p)
                    S.st.session_state[S.K_PLAN] = plan

    plan = S.st.session_state[S.K_PLAN]
    if plan is None:
        empty_state("No roadmap yet — click Generate to build one.")
        return

    card(
        "Plan summary",
        f"<span class='cg-muted'>{plan.summary}</span>"
        + (f"<br><br><b>Next action:</b> {plan.next_action}" if plan.next_action else ""),
        tags=[("watsonx", "info"), (f"{len(plan.milestones)} milestones", "ok")],
    )

    progress = S.st.session_state[S.K_MILESTONE_PROGRESS]
    if plan.milestones:
        done = sum(1 for v in progress.values() if v)
        st.progress(done / max(1, len(plan.milestones)), text=f"{done} / {len(plan.milestones)} milestones marked complete")

    for i, m in enumerate(plan.milestones, 1):
        # render styled step + a checkbox below to mark progress
        step(i, m.title, m.week_range, m.objectives, m.evidence, m.rationale)
        checked = st.checkbox(
            f"Mark Milestone {i} complete",
            value=progress.get(i - 1, False),
            key=f"ms_done_{i-1}",
        )
        progress[i - 1] = checked

    if plan.risks:
        card(
            "Risks the agent flagged",
            "<ul style='margin: 4px 0 0 18px;'>"
            + "".join(f"<li>{r}</li>" for r in plan.risks)
            + "</ul>",
            tags=[("Be aware", "warn")],
        )

    st.markdown('<div class="cg-divider"></div>', unsafe_allow_html=True)
    st.caption("Disagree with the plan? Tell the agent in Chat or refine your profile and re-plan.")
